import os

class Config:
	SUPABASE_URL = "https://nzfrskgdvdhdfghjtaks.supabase.co"
	SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZnJza2dkdmRoZGZnaGp0YWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MzAwMTMsImV4cCI6MjA2ODEwNjAxM30.Y9ub1e4oaIDoIGXxoAJkC_WJtZVxknSlRpOfID0EYVE"
	GITHUB_CLIENT_ID = "Ov23liT2qZNKci9rlbws"
	GITHUB_CLIENT_SECRET = "7da047280f8e78332efc5ee197b46aa1ea955202"
	APP_DATA_PATH = os.getenv("FLET_APP_STORAGE_DATA")
	APP_TEMP_PATH = os.getenv("FLET_APP_STORAGE_TEMP")
	APP_ASSETS_PATH = os.getenv("FLET_ASSETS_DIR")