import os

class Config:
	SUPABASE_URL = os.getenv("SUPABASE_URL", "")
	SUPABASE_KEY = os.getenv("SUPABASE_ANON_KEY", "")
	GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID", "")
	GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET", "")
	APP_DATA_PATH = os.getenv("FLET_APP_STORAGE_DATA")
	APP_TEMP_PATH = os.getenv("FLET_APP_STORAGE_TEMP")
	APP_ASSETS_PATH = os.getenv("FLET_ASSETS_DIR")